name: "waka-box"
description: "Update a pinned gist to contain WakaTime stats"
branding:
  icon: "clipboard"
  color: "blue"
runs:
  using: "node12"
  main: "dist/index.js"

- name: waka-box
  uses: matchai/waka-box@v4.0.3

